name: dbt Google Cloud Platform Setup
description: Authenticate to GCP, Install Python tooling and prepare dbt environment
author: Mathews Machado

inputs:
  gcp-project-id:
    required: true
    description: Google Cloud Platform Project Id
  gcp-workload-identity-provider:
    required: true
    description: Google Cloud Platform Workload Identity Provider
  gcp-service-account:
    required: true
    description: Google Cloud Platform Service Account
  gcp-artifacts-bucket-prd:
    required: true
    description: Google Cloud Storage Bucket for production artifacts

runs:
  using: composite
  steps:
    - uses: ./.github/actions/gcp-authenticate
      with:
        gcp-project-id: ${{ inputs.gcp-project-id }}
        gcp-workload-identity-provider: ${{ inputs.gcp-workload-identity-provider }}
        gcp-service-account: ${{ inputs.gcp-service-account }}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.21"
        enable-cache: true

    - name: Set up Python
      shell: bash
      working-directory: dbt_project
      run: uv python install

    - name: Install Python Dependencies
      shell: bash
      working-directory: dbt_project
      run: uv sync

    - name: Cache dbt Dependencies
      id: cache-dbt-dependencies
      uses: actions/cache@v4
      with:
        path: dbt_project/dbt_packages
        key: dbt_project/dbt_packages-${{ hashFiles('dbt_project/packages.yml') }}
        restore-keys: |
          dbt_project/dbt_packages-

    - name: Install dbt Dependencies
      if: steps.cache-dbt-dependencies.outputs.cache-hit != 'true'
      shell: bash
      working-directory: dbt_project
      run: uv run dbt deps

    - name: Download manifest.json
      shell: bash
      working-directory: dbt_project
      run: |
        gcloud storage cp \
          ${{ inputs.gcp-artifacts-bucket-prd }}/target/manifest.json \
          artifacts/manifest.json || true
          # {
          #   echo "No manifest.json found."
          #   exit 1
          # }
