# https://docs.getdbt.com/reference/dbt_project.yml
name: dbt_project
version: 1.0.0
profile: dbt_project

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

clean-targets:
  - target

# https://docs.getdbt.com/docs/build/project-variables
vars:
  dbt_date:time_zone: Etc/UTC

# https://docs.getdbt.com/reference/resource-configs/bigquery-configs#applying-labels-to-jobs
query-comment:
  comment: '{{ query_comment(node) }}'
  job-label: True

# https://docs.getdbt.com/reference/model-configs
models:
  dbt_project:
    +database: '{{ env_var("GCP_PROJECT_ID", "") }}'
    +materialized: table
    +on_schema_change: sync_all_columns
    +persist_docs:
      relation: True
      columns: True

# https://docs.getdbt.com/reference/seed-configs
# seeds:
#   dbt_project:
#     +persist_docs:
#       relation: True
#       columns: True
