dbt_project:
  target: '{{ env_var("DBT_TARGET") }}'
  outputs:
    dev:
      type: bigquery
      location: '{{ env_var("GCP_LOCATION") }}'
      project: '{{ env_var("GCP_PROJECT_ID") }}'
      dataset: dbt_project
      priority: interactive
      job_execution_timeout_seconds: 120
      job_retries: 1
      threads: 4
      method: oauth
      impersonate_service_account: '{{ env_var("GCP_CLIENT_EMAIL") }}'
