name: Authenticate Google Cloud Platform
description: Authenticate to Google Cloud Platform
author: Mathews Machado

inputs:
  gcp-project-id:
    required: true
    description: Google Cloud Platform Project Id
  gcp-workload-identity-provider:
    required: true
    description: Google Cloud Platform Workload Identity Provider
  gcp-service-account:
    required: true
    description: Google Cloud Platform Service Account

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud Platform
      uses: google-github-actions/auth@v3
      with:
        project_id: ${{ inputs.gcp-project-id }}
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account }}
