name: Comment Terraform Command Output on Pull Request
description: Comment Terraform Command Output on Pull Request
author: Mathews Machado

inputs:
  terraform-project:
    required: true
    description: Terraform Project
  terraform-command:
    required: true
    description: Terraform Command
  terraform-command-outcome:
    required: true
    description: Terraform Command Outcome
  terraform-command-stdout:
    required: true
    description: Terraform Command Stdout
  terraform-command-stderr:
    required: true
    description: Terraform Command Stderr

runs:
  using: composite
  steps:
    - name: Comment Terraform Command Output on Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const body = `
          ## Terraform Comment

          **Project:** ${{ inputs.terraform-project }}

          **Command:** ${{ inputs.terraform-command }}

          **Outcome:** ${{ inputs.terraform-command-outcome }}

          <details>
            <summary>
              <b>Output: </b>
            </summary>

            <pre>${{ inputs.terraform-command-stdout }}${{ inputs.terraform-command-stderr }}</pre>
          </details>
          `

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          })
