name: Comment Terraform Command Result on Pull Request
description: Comment Terraform Command Result on Pull Request
author: Mathews Machado

inputs:
  terraform-project:
    required: true
    description: Terraform Project
  terraform-command:
    required: true
    description: Terraform Command
  terraform-command-outcome:
    required: true
    description: Terraform Command Outcome
  terraform-command-stdout:
    required: true
    description: Terraform Command Stdout
  terraform-command-stderr:
    required: true
    description: Terraform Command Stderr

runs:
  using: composite
  steps:
    - name: Comment Terraform Command Result on Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const body = `
          <h2>Terraform Comment</h2>

          <ul>
            <li>
              <b>Terraform Project: </b>
              <span>${{ inputs.terraform-project }}</span>
            </li>

            <li>
              <b>Terraform Command: </b>
              <span>${{ inputs.terraform-command }}</span>
            </li>

            <li>
              <b>Terraform Command Outcome: </b>
              <span>${{ inputs.terraform-command-outcome }}</span>
            </li>
            <li>
              <details>
                <summary>
                  <b>Terraform Command Output: </b>
                </summary>

                <pre>${{ inputs.terraform-command-stdout }}${{ inputs.terraform-command-stderr }}</pre>
              </details>
            </li>
          </ul>
          `

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          })
