name: dbt Deploy Project Production

on:
  push:
    branches:
      - main
    paths:
      - dbt_project/**

jobs:
  dbt-project-deploy-prd:
    uses: ./.github/workflows/dbt-project-deploy.yml
    with:
      environment: prd
