name: dbt Project Run Production

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  dbt-project-run-prd:
    runs-on: ubuntu-latest
    environment: prd

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5

      - uses: ./.github/actions/gcp-authenticate
        with:
          gcp-project-id: ${{ vars.GCP_PROJECT_ID }}
          gcp-workload-identity-provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp-service-account: ${{ vars.GCP_SERVICE_ACCOUNT_DBT_PROJECT }}

      - name: Generate dbt Variables
        id: dbt-vars
        run: |
          echo "_processed_at=$(date '+%Y-%m-%d %H:%M:%S.%6N')" >> $GITHUB_OUTPUT
          echo "execution_date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "pepper=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)" >> $GITHUB_OUTPUT

      - name: Trigger Cloud Run Job
        run: |
          gcloud run jobs execute dbt-project \
            --region=us-central1 \
            --args="run,--vars,{\"_processed_at\": \"${{ steps.dbt-vars.outputs._processed_at }}\", \"execution_date\": \"${{ steps.dbt-vars.outputs.execution_date }}\", \"pepper\": \"${{ steps.dbt-vars.outputs.pepper }}\"}" \
            --async
