name: Deploy dbt Project Production

on:
  push:
    branches:
      - main
    paths:
      - dbt_project/**

jobs:
  dbt-project-deploy-prd:
    uses: ./.github/workflows/deploy-dbt-project.yml
    with:
      gcp-project-id: mathews-mrr-prd
      gcp-workload-identity-provider: projects/489693200516/locations/global/workloadIdentityPools/github/providers/mathews-mrr
      gcp-service-account: dbt-project@mathews-mrr-prd.iam.gserviceaccount.com
      gcp-artifacts-bucket: gs://mathews-mrr-prd-dbt-project-bucket
      gcp-artifacts-bucket-prd: gs://mathews-mrr-prd-dbt-project-bucket
