name: Deploy Terraform Production

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/modules/**
      - terraform/shared/**
      - terraform/projects/mathews-mrr-prd/**

jobs:
  deploy-terraform-prd:
    uses: ./.github/workflows/deploy-terraform.yml
    with:
      gcp-project-id: mathews-mrr-prd
      gcp-workload-identity-provider: projects/489693200516/locations/global/workloadIdentityPools/github/providers/mathews-mrr
      gcp-service-account: terraform@mathews-mrr-prd.iam.gserviceaccount.com
      terraform-project: terraform/projects/mathews-mrr-prd
