name: Deploy Terraform Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/modules/**
      - terraform/shared/**
      - terraform/projects/mathews-mrr-stg/**

jobs:
  deploy-terraform-stg:
    uses: ./.github/workflows/deploy-terraform.yml
    with:
      gcp-project-id: mathews-mrr-stg
      gcp-workload-identity-provider: projects/398127736452/locations/global/workloadIdentityPools/github/providers/mathews-mrr
      gcp-service-account: terraform@mathews-mrr-stg.iam.gserviceaccount.com
      terraform-project: terraform/projects/mathews-mrr-stg
