name: Deploy dbt Project Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - dbt_project/**

jobs:
  dbt-project-deploy-stg:
    uses: ./.github/workflows/deploy-dbt-project.yml
    with:
      gcp-project-id: mathews-mrr-stg
      gcp-workload-identity-provider: projects/398127736452/locations/global/workloadIdentityPools/github/providers/mathews-mrr
      gcp-service-account: dbt-project@mathews-mrr-stg.iam.gserviceaccount.com
      gcp-artifacts-bucket: gs://mathews-mrr-stg-dbt-project-bucket
      gcp-artifacts-bucket-prd: gs://mathews-mrr-prd-dbt-project-bucket
