name: Terraform Deploy Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/modules/**
      - terraform/shared/**
      - terraform/projects/mathews-mrr-stg/**

jobs:
  deploy-terraform-stg:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: stg
